name: Авто-загрузка на PyPI

on:
  release:
    types: [published,prereleased]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Сборка пакета
      run: |
        python -m build
    
    - name: Загрузка на PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
